#!/bin/sh

set -e

insmod /capstone.ko
DOM_NAME=$1
if [ -f /test-domains/$DOM_NAME.smode ]; then
    /capstone-test.user /test-domains/$DOM_NAME.dom $2 /test-domains/$DOM_NAME.smode
else
    /capstone-test.user /test-domains/$DOM_NAME.dom $2
fi
rmmod capstone
