CAPSTONE_RUNTIME_VERSION = 1
CAPSTONE_RUNTIME_SITE = $(call qstrip,$(BR2_PACKAGE_CAPSTONE_RUNTIME_SOURCE))/capstone/runtime
CAPSTONE_RUNTIME_SITE_METHOD = local
CAPSTONE_RUNTIME_SUBDIR = exec
CAPSTONE_RUNTIME_DEPENDENCIES = modcapstone
CAPSTONE_RUNTIME_CONF_OPTS = -DBUILD_TESTING=OFF \
	-DCAPSTONE_LIBCAPSTONE_DIR=$(MODCAPSTONE_DIR)/userspace/lib

ifeq ($(BR2_PACKAGE_CAPSTONE_RUNTIME),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_CAPSTONE_RUNTIME_SOURCE)),)
$(error BR2_PACKAGE_CAPSTONE_RUNTIME_SOURCE must name the LLVM Capstone checkout)
endif
endif

define CAPSTONE_RUNTIME_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(CAPSTONE_RUNTIME_PKGDIR)/S40capstone \
		$(TARGET_DIR)/etc/init.d/S40capstone
endef

$(eval $(cmake-package))
