#ifndef __CAPSTONE_SBI_H_
#define __CAPSTONE_SBI_H_


#define SBI_EXT_CAPSTONE 0x12345678

#define SBI_EXT_CAPSTONE_DOM_CREATE 0x0
#define SBI_EXT_CAPSTONE_DOM_CALL   0x1
#define SBI_EXT_CAPSTONE_DOM_CALL_WITH_CAP   0x2


#endif
